# 1. Configuración local (para que lo puedas probar en tu compu ahora)
backend:
  name: git-gateway
  branch: main
local_backend: true

# 2. ¿Dónde se guardan las FOTOS NUEVAS que suba tu equipo?
media_folder: "public/img/blog"
public_folder: "/img/blog"

# 3. ¿Qué campos tiene que llenar el redactor?
collections:
  - name: "actualidad"
    label: "Noticias de Actualidad"
    folder: "src/noticias/actualidad"
    create: true
    extension: "mdx"
    format: "frontmatter"
    fields:
      - {label: "Título de la Noticia", name: "title", widget: "string"}
      - {label: "Copete (Frase marketinera)", name: "description", widget: "text", required: false}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Imagen de Portada", name: "image", widget: "image", required: false}
      - {label: "Cuerpo de la Noticia", name: "body", widget: "markdown"}